---
title: "편의점 브랜드 GS25"
subtitle: "-GS25 기사 보도가 나아가야 할 방향 제안-"
author: "언론홍보학과 4학년 김수진(2018102101)"
format:
  revealjs:
    incremental: false  
    theme: dark
---

## 목차
1. 개요
- 언론보도분석을 통한 편의점 3사 평판 비교분석
- 언론보도 분석을 통한 GS25의 연도별 평판 비교분석
- 언론보도 분석을 통한 편의점의 연도별 이슈 및 트렌드 비교분석
- 결론 : GS25 기사 보도가 나아가야 할 방향 제안
2. 편의점 트렌드
3. GS25의 기사 보도 및 평판관리 상황
4. 결론 : GS25 기사 보도가 나아가야 할 방향 제안

# 1. 개요
---

### 1) 언론보도분석을 통한 편의점 3사 평판 비교분석
- 분석 주제 선정 이유
  - 대형마트, 중형마트, 온라인 커머스, 편의점 등 커머스의 다양화가 진행됨.그 중에서도 편의점은 소비자들의 생활반경 근처에 다수 포진해있음에 따라 적극적인 변화를 모색하고 있음. 각각의 편의점의 평판을 분석하여 어떠한 차이를 보이고 있는지 살펴보고자 함.
---

- 자료 분석 방법
  - 자료 유형 : 뉴스 (정치, 사회, 스포츠 뉴스 제외)
  - 자료 출처 : 빅카인즈
  - 자료 기간 : 2021. 09. 01. \~ 2022. 09. 30. (약 1년간)
  - 자료수집

:::: {.columns}

::: {.column width="33%"}
  1)  GS25
   -   검색어 : ((GS25) OR (지에스25) OR (gs25) OR (지에스이십오))
   -   총 4416건의 기사
:::

::: {.column width="33%"}
  2)  세븐일레븐
  -   검색어 : ((코리아세븐) OR (Korea Seven Co.) OR ((주)코리아세븐) OR (주식회사 코리아세븐) OR (세븐일레븐))
  -   총 3520건의 기사
:::

::: {.column width="33%"}
  3)  CU
  -   검색어 : ((CU편의점) OR (CU) OR (CU 편의점))
  -   총 5241건의 기사
:::
::::
---

### 2) 언론보도 분석을 통한 GS25의 연도별 평판 비교분석

- 분석 주제 선정 이유
  - 2022년 10월 한국기업평판연구소에 따르면, 1위 CU, 2위 세븐일레븐, 4위 GS25로 편의점 브랜드 순위를 발표함. 브랜드 순위가 낮은 GS25에 효과적인 평판 관리를 제안하고자 이를 중심으로 추가 분석을 하고자 함.
---

- 자료 분석 방법
  - 자료 유형 : 뉴스 (정치, 사회, 스포츠 뉴스 제외)
  - 자료 출처 : 빅카인즈
  - 자료수집

:::: {.columns}

::: {.column width="50%"}
  1)  GS25 (2021)
  -   검색어 : ((GS25) OR (지에스25) OR (gs25) OR (지에스이십오))
  -   자료 기간 : 2021. 01. 01. \~ 2021. 10. 31. (약 10개월)
  -   총 3883건의 기사
:::

::: {.column width="50%"}
   2)  GS25 (2022)
   -   검색어 : ((GS25) OR (지에스25) OR (gs25) OR (지에스이십오))
   -   자료 기간 : 2022. 01. 01. \~ 2022. 10. 31. (약 10개월)
   -   총 3532건의 기사
:::

::::
---

### 3) 언론보도 분석을 통한 편의점의 연도별 이슈 및 트렌드 비교분석

- 분석 주제 선정 이유
  - 편의점들의 사업확장 및 기업 인수를 통해 경쟁이 더 심화되고 있음을 확인함. 이 가운데 GS25가 편의점 트렌드에 맞춰 평판관리를 진행하고 있는지 살펴보기 위해 '편의점의 연도별 이슈 및 트렌드'를 살펴보려고 함.
---

- 자료 분석 방법
  - 자료 유형 : 뉴스 (정치, 사회, 스포츠 뉴스 제외)
  - 자료 출처 : 빅카인즈
  - 자료수집

:::: {.columns}

::: {.column width="50%"}
   1)  편의점 (2021)
  -   검색어 : 편의점
  -   자료 기간 : 2021. 01. 01. \~ 2021. 10. 31. (약 10개월)
  -   총 3883건의 기사
:::

::: {.column width="50%"}
  2)  편의점 (2022)
  -   검색어 : 편의점
  -   자료 기간 : 2022. 01. 01. \~ 2022. 10. 31. (약 10개월)
  -   총 3532건의 기사
:::

::::
---

# 2. 편의점 트렌드


```{r}
#install.packages("png")
library(png)

#trend.array <- readPNG(system.file("토픽모델링_GS25-1", "토픽모델링_세븐일레븐-1", "토픽모델링_CU-1", package="png"))
#class(trend.array)
```



# 3. GS25의 기사 보도 및 평판관리 상황





# 4. 결론 : GS25 기사 보도가 나아가야 할 방향 제안










## Getting up

- Turn off alarm
- Get out of bed

## Breakfast

- Eat eggs
- Drink coffee

# In the evening

## Dinner

- Eat spaghetti
- Drink wine

::: {.incremental}

- Eat spaghetti
- Drink wine

:::

::: {.nonincremental}

- Eat spaghetti
- Drink wine

:::
---