---
title: "2nd_data"
format: html
editor: visual
---

## 1. 자료수집

-   기간 : 2022. 08. 01 \~ 2022. 09. 17.
-   데이터 수집 출처 : 빅카인즈
-   통합뉴스 크롤링 (정치, 사회, 스포츠 뉴스 제외)
```{r}
# install.packages("tidytext")
# install.packages("tidyverse")
install.packages("dplyr")
library(tidytext)
library(tidyverse)
library(dplyr)
```


### 1) GS25
```{r}
#자료준비
GS25_test_data1 <- readxl::read_excel('GS25_test_data.xlsx')
GS25_test_data2 <- GS25_test_data1[,17]
GS25_df <- tibble(text = GS25_test_data2)


# 정제(토큰화) 및 분석
GS25_df <- GS25_df %>%
  mutate_all(as.character) %>% 
  pos(join = FALSE)

GS25_tk <- GS25_df %>% 
  mutate_all(as.character) %>% 
  unnest_tokens(word, text) %>%
  count(word, sort = TRUE)

#install.packages("kableExtra")
#install.packages('RcppMeCab')
library(RcppMeCab)
GS25_tk %>% posParallel(format = "data.frame")

GS25_tk %>% pos(join = FALSE)


# 막대도표 시각화
GS25_word_top15 <-GS25_tk %>%
  head(15)
  
GS25_word_top15 %>%
  filter(n >= 4) %>% 
  mutate(word = reorder(word, n)) %>% 
  ggplot(aes(word, n)) +
  geom_col() +
  coord_flip()
                  
```



```{r}
#install.packages("readxl")

GS25_test_data1 <- readxl::read_excel('GS25_test_data.xlsx')
GS25_test_data2 <- GS25_test_data1[,17]
colnames(GS25_test_data2) <- c("body")
```

### 2) 세븐일레븐
```{r}
#자료준비
seven_test_data1 <- readxl::read_excel('seveneleven_test_data.xlsx')
seven_test_data2 <- seven_test_data1[,17]
seven_df <- tibble(text = seven_test_data2)


# 정제(토큰화) 및 분석
seven_tk <- seven_df %>% 
  mutate_all(as.character) %>% 
  unnest_tokens(word, text) %>%
  count(word, sort = TRUE)


# 막대도표 시각화
seven_word_top15 <-seven_tk %>%
  head(15)
  
seven_word_top15 %>%
  filter(n >= 4) %>% 
  mutate(word = reorder(word, n)) %>% 
  ggplot(aes(word, n)) +
  geom_col() +
  coord_flip()
```



```{r}
#install.packages("readxl")

seven_test_data1 <- readxl::read_excel('seveneleven_test_data.xlsx')
seven_test_data2 <- seven_test_data1[,17]
colnames(seven_test_data2) <- c("body")
```

### 3) CU
```{r}
#자료준비
CU_test_data1 <- readxl::read_excel('CU_test_data.xlsx')
CU_test_data2 <- CU_test_data1[,17]
CU_df <- tibble(text = CU_test_data2)


# 정제(토큰화) 및 분석
CU_tk <- CU_df %>% 
  mutate_all(as.character) %>% 
  unnest_tokens(word, text) %>%
  count(word, sort = TRUE)


# 막대도표 시각화
CU_word_top15 <-CU_tk %>%
  head(15)
  
CU_word_top15 %>%
  filter(n >= 4) %>% 
  mutate(word = reorder(word, n)) %>% 
  ggplot(aes(word, n)) +
  geom_col() +
  coord_flip()
```



```{r}
#install.packages("readxl")

CU_test_data1 <- readxl::read_excel('CU_test_data.xlsx')
CU_test_data2 <- CU_test_data1[,17]
colnames(CU_test_data2) <- c("body")
```

## 2. 형태소 분석

### 1) 기본 세팅

```{r}
library(multilinguer)

#install.packages(c("stringr", "hash", "tau", "Sejong", "RSQLite", "devtools"), type = "binary")

#install.packages("remotes")
#remotes::install_github("haven-jeon/KoNLP", upgrade = "never", INSTALL_opts = c("--no-multiarch"))

library(KoNLP)
#useNIADic()

#install.packages("dplyr")
library(dplyr)

#install.packages("tidytext")
library(tidytext)

library(stringr)

#install.packages("textclean")
library(textclean)
```

### 2) GS25

```{r}
GS25_test_data3 <- GS25_test_data2 %>%
  as_tibble()

GS25_test_data4 <- GS25_test_data3 %>%
  unnest_tokens(input = body,
                output = GS25_word)

```

### 3) 세븐일레븐

```{r}
seven_test_data3 <- seven_test_data2 %>%
  as_tibble()

seven_test_data4 <- seven_test_data3 %>%
  unnest_tokens(input = body,
                output = seven_word)

```

### 4) CU

```{r}
CU_test_data3 <- CU_test_data2 %>%
  as_tibble()

CU_test_data4 <- CU_test_data3 %>%
  unnest_tokens(input = body,
                output = CU_word)

```

## 3. 단어 빈도 구하기

### 1) GS25

```{r}

GS25_df %>% 
  count(word, sort = TRUE) %>% 
  filter(n > 1) %>% 
  mutate(word = reorder(word, n)) %>% 
  ggplot(aes(word, n)) +
  geom_col() +
  coord_flip()
```


```{r}
GS25_test_data5 <- GS25_test_data4 %>%
  count(GS25_word, sort = T) %>%
  filter(str_count(GS25_word) > 1)

GS25_word_top15 <- GS25_test_data5 %>%
  head(15)

library(ggplot2)
ggplot(GS25_word_top15, aes(x = reorder(GS25_word,n), y=n)) +
  geom_col() +
  coord_flip() +
  geom_text(aes(label=n), size=4, hjust=1.3) +
  labs(title = 'GS25 단어 출연 빈도', x = '등장 단어', y = '등장 빈도수')

```

### 2) 세븐일레븐

```{r}
seven_test_data5 <- seven_test_data4 %>%
  count(seven_word, sort = T) %>%
  filter(str_count(seven_word) > 1)

seven_word_top15 <- seven_test_data5 %>%
  head(15)

library(ggplot2)
ggplot(seven_word_top15, aes(x = reorder(seven_word,n), y=n)) +
  geom_col() +
  coord_flip() +
  geom_text(aes(label=n), size=4, hjust=1.3) +
  labs(title = '세븐일레븐 단어 출연 빈도', x = '등장 단어', y = '등장 빈도수')

```

### 3) CU

```{r}
CU_test_data5 <- CU_test_data4 %>%
  count(CU_word, sort = T) %>%
  filter(str_count(CU_word) > 1)

CU_word_top15 <- CU_test_data5 %>%
  head(15)

library(ggplot2)
ggplot(CU_word_top15, aes(x = reorder(CU_word,n), y=n)) +
  geom_col() +
  coord_flip() +
  geom_text(aes(label=n), size=4, hjust=1.3) +
  labs(title = 'CU 단어 출연 빈도', x = '등장 단어', y = '등장 빈도수')

```

## 4. 비교분석

### 1)
